### ISSUE TITLE
Is this a bug ?

### ISSUE THREAD

**Issue by HuangZuShu** [xuanqing94/AdvGAN#9]
https://github.com/xuanqing94/RobGAN/blob/8a478cf3435387753baee2d3a82d039236cc4fab/acc_under_attack.py#L65

When evaluating, the test data should be used.

So the correct should be as following:

```python
data = CIFAR10(root=opt.root, train=False, download=False, transform=trans)
```

**Comment by xuanqing94** [comment]
Hey, thanks for reaching out.

It was many years ago from now, but I vaguely remember I change `train=False` to `True` because I need to compute the train/valid accuracy gap in Figure 6 (right subplot) of our paper. 

Ideally I need to pass the option from argument parser but I simply changed the parameter manually. If you want to reproduce our results then please also follow the same procedure.

**Comment by HuangZuShu** [comment]
Thank you for your explanation.
